### ISSUE TITLE
How can I get selected values "onchange" event?

### ISSUE THREAD

**Issue by mikelweb** [rajpurohitgs/multi-select#2]
Hi,
How can I get selected values "onchange" event?

I don't know how to get selected values onSelect callback function

Thx!

**Comment by gsrajpurohit** [comment]
Hello
Thanks for your email.

You can use onSelect function to get the selected values. This function
accept one argument that is an array. It returns the selected values.
You can use like this......
onSelect: function (values){

}

If have any query with this approach please let me know.

Again thank you for your interest.

Regards
GS Rajpurohit

**Comment by mikelweb** [comment]
Perfect, thank you!!
